# MySQL. Versions 5.0 and up are supported.
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: sqlpassword
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: rEstates_development


test:
  <<: *default
  database: rEstates_test


production:
  <<: *default
  database: rEstates_production
  username: rEstates
  password: <%= ENV['RESTATES_DATABASE_PASSWORD'] %>
